### ISSUE TITLE
Implement Sub<time::Duration> for chrono::DateTime

### ISSUE THREAD

**Issue by sereinity** [chronotope/chrono#488]
Since the update on time crate to 0.2 (see also #400)

I cannot do math operation (substraction/add) between a time::Duration and a DateTime.

```
error[E0277]: cannot subtract `time::Duration` from `chrono::DateTime<chrono::Utc>`
   --> src/main.rs:109:29
    |
109 |         let max_date = time - Duration::days(keep_days.into());
    |                             ^ no implementation for `chrono::DateTime<chrono::Utc> - time::Duration`
    |
    = help: the trait `Sub<time::Duration>` is not implemented for `chrono::DateTime<chrono::Utc>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

**Comment by pitdicker** [comment]
Sorry for the late reply, I am going through old issues.

Chrono is moving away from the `Duration` type of the `time` crate.
You may want to use `chrono::Duration` to do math operations on `DateTime`s.
