### ISSUE TITLE
Release 0.3 broke subtraction

### ISSUE THREAD

**Issue by dgrnbrg** [chronotope/chrono#127]
My code worked on chrono 0.2. It appears that subtracting 2 DateTimes no longer results in a Duration.

```
error[E0277]: the trait bound `chrono::DateTime<chrono::UTC>: std::ops::Sub` is not satisfied
   --> src/processor/mod.rs:166:52
    |
166 |             since_last: instant - self.now,
    |                         ^^^^^^^^^^^^^^^^^^ the trait `std::ops::Sub` is not implemented for `chrono::DateTime<chrono::UTC>`
    |
    = help: the following implementations were found:
              <chrono::DateTime<Tz> as std::ops::Sub<chrono::FixedOffset>>
              <chrono::DateTime<Tz> as std::ops::Sub<time::Duration>>
```

**Comment by lifthrasiir** [comment]
It's intentional and replaced by `instant.signed_duration_since(self.now)`. See the [`CHANGELOG.md`](https://github.com/chronotope/chrono/blob/db9b98f691c858ab0929accff11263e1dcedbeb0/CHANGELOG.md). (The primary reason is that we plan to move `std::time::Duration` during 0.3.x.)
