### ISSUE TITLE
0.4.37 semver-incompatibly removes trait bounds on `DateTime`

### ISSUE THREAD

**Issue by little-dude** [chronotope/chrono#1571]
Hello,

The following code compile in 0.4.35 but breaks in 0.4.37:

```rust
use chrono::TimeZone;
use chrono::DateTime;

#[derive(Clone, Debug)]
pub struct MyDateTime<T: TimeZone>(DateTime<T>);

impl<T: TimeZone> Copy for MyDateTime<T> where T::Offset: Copy {}
```

With 0.4.37:
```
error[E0204]: the trait `Copy` cannot be implemented for this type
 --> src/main.rs:7:28
  |
5 | pub struct MyDateTime<T: TimeZone>(chrono::DateTime<T>);
  |                                    ------------------- this field does not implement `Copy`
6 |
7 | impl<T: TimeZone> Copy for MyDateTime<T> where T::Offset: Copy {}
  |                            ^^^^^^^^^^^^^
  |
note: the `Copy` impl for `DateTime<T>` requires that `T: Copy`
 --> src/main.rs:5:36
  |
5 | pub struct MyDateTime<T: TimeZone>(chrono::DateTime<T>);
  |                                    ^^^^^^^^^^^^^^^^^^^
help: consider further restricting this bound
  |
7 | impl<T: TimeZone + Copy> Copy for MyDateTime<T> where T::Offset: Copy {}
```
This is probably due to https://github.com/chronotope/chrono/pull/1492

**Comment by djc** [comment]
Sorry for the regression! We'll look into this. I don't think we're going to just revert the changes for #1492, but let's see what we can do.

**Comment by little-dude** [comment]
No worries, it's not a big deal for me. I just thought opening an issue might be good if other people run into this.

**Comment by djc** [comment]
Right -- I think I'm inclined to let this one go unless there are multiple reporters for whom it turns out to be a larger problem. As I understand it, it mostly requires people add bounds that they should have been adding anyway.

**Comment by pitdicker** [comment]
The manual `Copy` implementation that was deleted in #1492 was sound, it was only the comment that was incorrect. We had it because the type of `Tz` doesn't matter as it isn't a field of the `DateTime` struct.

For the `Send` implementation I'm not 100% sure it was sound.

**Comment by pitdicker** [comment]
Reverting the change to `Copy` is easy, shall I just make a PR?

**Comment by little-dude** [comment]
Yeah I agree that the previous `Copy` impl was better than the derived one. Wdyt @djc ?

**Comment by djc** [comment]
Alright, sounds good.

I think the `Send` impl was also sound but somewhat accidentally sound -- it might've become unsound if we changed the layout of `NaiveDateTime`.

**Comment by little-dude** [comment]
OOC how could a `Copy` impl be unsound? It isn't an unsafe trait, so I assumed it couldn't be unsound.

**Comment by pitdicker** [comment]
Sorry, I'm not using the right term. Meant 'correct'.

**Comment by little-dude** [comment]
Thanks for the quick response on this @pitdicker and @djc !
